### ISSUE TITLE
Cannot bundle a plugin with tyk gateway v5.5.0

### ISSUE THREAD

**Issue by mcsuka** [TykTechnologies/custom-go-plugin#26]
As the tyk gateway container image is now shipped without a shell (https://tyk.io/docs/product-stack/tyk-gateway/release-notes/version-5.5/#breaking-changes), we are unable to bundle Go plugins for v5.5.
The `make bundle` process  is trying to run a shell script in the tyk-gateway container, which fails:
`docker-compose run --rm --user=$(DOCKER_USER) --entrypoint "bundle/bundle-entrypoint.sh" tyk-gateway`

https://github.com/TykTechnologies/custom-go-plugin/blob/65cbc70e09cf37c4d3a2110677f6dcf2bbb9e51a/Makefile#L141-L146

Could you please provide an alternative way of bundling Go plugins in the makefile?

**Comment by buger** [comment]
@mcsuka I believe it may fix the issue https://github.com/TykTechnologies/custom-go-plugin/pull/27/files, if you can test it out will be great!

**Comment by mcsuka** [comment]
@buger the fix is working, thanks!
